app:
  open-endpoints: ${OPEN_ENDPOINTS:true}
server:
  port: ${PORT:8050}
bot:
  name: ${BOT_NAME}
  token: ${BOT_TOKEN}
minecraft:
  server:
    address: ${MINECRAFT_SERVER_ADDRESS}
    port: ${MINECRAFT_SERVER_PORT:25565}
spring:
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: ${DB_URL}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    baseline-on-migrate: true
    out-of-order: true