CREATE TABLE IF NOT EXISTS player
(
    id   TEXT NOT NULL PRIMARY KEY,
    name TEXT
);

CREATE TABLE IF NOT EXISTS server_event
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action    TEXT,
    time      TIMESTAMP,
    player_id TEXT CONSTRAINT server_event_player_fk REFERENCES player
);

CREATE TABLE IF NOT EXISTS server_info_downtime
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    downtime TIMESTAMP,
    error    TEXT,
    uptime   TIMESTAMP
);

CREATE TABLE IF NOT EXISTS server_stats
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    max_players    INTEGER NOT NULL,
    name           TEXT,
    online_players INTEGER NOT NULL,
    protocol       TEXT,
    text           TEXT
);

CREATE TABLE IF NOT EXISTS server_stats_players_online
(
    server_stats_id   BIGINT NOT NULL CONSTRAINT server_stats_fk REFERENCES server_stats,
    players_online_id TEXT NOT NULL CONSTRAINT player_fk REFERENCES player
);

CREATE TABLE IF NOT EXISTS telegram_user
(
    id             BIGINT NOT NULL PRIMARY KEY,
    bot_state      TEXT,
    first_name     TEXT,
    is_bot         BOOLEAN NOT NULL,
    last_name      TEXT,
    minecraft_name TEXT,
    user_name      TEXT
);

CREATE TABLE IF NOT EXISTS subscription
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type             TEXT,
    telegram_user_id BIGINT CONSTRAINT subscription_telegram_user_fk REFERENCES telegram_user
);

CREATE TABLE IF NOT EXISTS player_alias
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alias     TEXT,
    player_id TEXT CONSTRAINT player_alias_player_fk REFERENCES player,
    user_id   BIGINT CONSTRAINT player_alias_telegram_user_fk REFERENCES telegram_user
);
